export const cityOptions = [
  { name: "Delhi", code: "DEL", state: "Delhi" },
  { name: "Mumbai", code: "BOM", state: "Maharashtra" },
  { name: "Chennai", code: "MAA", state: "Tamil Nadu" },
  { name: "Kolkata", code: "CCU", state: "West Bengal" },
  { name: "Bangalore", code: "BLR", state: "Karnataka" },
  { name: "Hyderabad", code: "HYD", state: "Telangana" },
  { name: "Ahmedabad", code: "AMD", state: "Gujarat" },
  { name: "Jaipur", code: "JAI", state: "Rajasthan" },
  { name: "Varanasi", code: "VNS", state: "Uttar Pradesh" },
  { name: "Goa", code: "GOI", state: "Goa" },
  { name: "Lucknow", code: "LKO", state: "Uttar Pradesh" },
  { name: "Amritsar", code: "ATQ", state: "Punjab" },
  { name: "Pune", code: "PNQ", state: "Maharashtra" },
  { name: "Surat", code: "STV", state: "Gujarat" },
  { name: "Kanpur", code: "KNU", state: "Uttar Pradesh" },
  { name: "Nagpur", code: "NAG", state: "Maharashtra" },
  { name: "Indore", code: "IDR", state: "Madhya Pradesh" },
  { name: "Thane", code: "THN", state: "Maharashtra" },
  { name: "Bhopal", code: "BHO", state: "Madhya Pradesh" },
  { name: "Patna", code: "PAT", state: "Bihar" },
  { name: "Vadodara", code: "BDQ", state: "Gujarat" },
  { name: "Ghaziabad", code: "GZB", state: "Uttar Pradesh" },
  { name: "Ludhiana", code: "LDH", state: "Punjab" },
  { name: "Agra", code: "AGR", state: "Uttar Pradesh" },
  { name: "Nashik", code: "NSK", state: "Maharashtra" },
  { name: "Faridabad", code: "FBD", state: "Haryana" },
  { name: "Meerut", code: "MRT", state: "Uttar Pradesh" },
  { name: "Rajkot", code: "RJT", state: "Gujarat" },
  { name: "Kalyan", code: "KYN", state: "Maharashtra" },
  { name: "Vasai", code: "VSI", state: "Maharashtra" },
  { name: "Jabalpur", code: "JBP", state: "Madhya Pradesh" },
  { name: "Ujjain", code: "UJN", state: "Madhya Pradesh" },
  { name: "Gwalior", code: "GWL", state: "Madhya Pradesh" },
  { name: "Howrah", code: "HWH", state: "West Bengal" },
  { name: "Guwahati", code: "GHY", state: "Assam" },
  { name: "Bhubaneswar", code: "BBS", state: "Odisha" },
  { name: "Cuttack", code: "CTC", state: "Odisha" },
  { name: "Rourkela", code: "ROU", state: "Odisha" },
  { name: "Jamshedpur", code: "JSR", state: "Jharkhand" },
  { name: "Ranchi", code: "RNC", state: "Jharkhand" },
  { name: "Dhanbad", code: "DHN", state: "Jharkhand" },
  { name: "Thiruvananthapuram", code: "TVC", state: "Kerala" },
  { name: "Kochi", code: "COK", state: "Kerala" },
  { name: "Kozhikode", code: "CLT", state: "Kerala" },
  { name: "Vijayawada", code: "BZA", state: "Andhra Pradesh" },
  { name: "Visakhapatnam", code: "VSKP", state: "Andhra Pradesh" },
  { name: "Tirupati", code: "TPTY", state: "Andhra Pradesh" },
  { name: "Madurai", code: "MDU", state: "Tamil Nadu" },
  { name: "Coimbatore", code: "CBE", state: "Tamil Nadu" },
  { name: "Salem", code: "SA", state: "Tamil Nadu" },
  { name: "Jodhpur", code: "JU", state: "Rajasthan" },
  { name: "Udaipur", code: "UDZ", state: "Rajasthan" },
  { name: "Ajmer", code: "AII", state: "Rajasthan" },
];
